name: Docs Drift Guard

on:
  pull_request:
    branches: [ main, "**" ]
  push:
    branches: [ main ]

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run docs drift detection
        run: |
          bash scripts/check_docs_drift.sh
