name: pr-hygiene
on: [pull_request]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block deletion of workflows without owner approval
        run: |
          base=${{ github.event.pull_request.base.sha }}
          head=${{ github.event.pull_request.head.sha }}
          DELETED=$(git diff --diff-filter=D --name-only "$base" "$head" | grep '^.github/workflows/' || true)
          if [ -n "$DELETED" ]; then
            echo "Workflows removed: "; echo "$DELETED"
            echo "Refusing PR unless CODEOWNERS approves."
            exit 1
          fi
      - name: Require journal & docs with code changes
        run: |
          base=${{ github.event.pull_request.base.sha }}
          head=${{ github.event.pull_request.head.sha }}
          CHANGES=$(git diff --name-only "$base" "$head")
          if echo "$CHANGES" | grep -qE '^(src|systemd|scripts|web-ui)/'; then
            echo "$CHANGES" | grep -q '^memory/AGENT_JOURNAL.md' || (echo "Missing AGENT_JOURNAL update" && exit 1)
            echo "$CHANGES" | grep -q '^docs/' || (echo "Missing docs update" && exit 2)
          fi
