"""
Models package for LawnBerry Pi v2
Pydantic models for all system entities
"""

from .ai_processing import (
    AcceleratorStatus,
    AIAccelerator,
    AIProcessing,
    BoundingBox,
    DetectedObject,
    InferenceResult,
    InferenceTask,
    ModelFormat,
    ModelInfo,
    ModelStatus,
)
from .camera_stream import (
    CameraCapabilities,
    CameraConfiguration,
    CameraFrame,
    CameraMode,
    CameraStream,
    FrameFormat,
    FrameMetadata,
    StreamQuality,
    StreamStatistics,
)
from .control_session import (
    ControlAuditEntry,
    ControlCommand,
    ControlCommandResult,
    ControlCommandType,
    ControlSession,
    EmergencyState,
    EmergencyStatus,
    SafetyInterlock,
)
from .coverage_pattern import CoveragePattern
from .geofence import Geofence, LatLng
from .hardware_baseline import (
    AIAcceleratorType,
    ComponentStatus,
    DriveControllerType,
    GPIOPinAssignment,
    GpsModuleType,
    HardwareBaseline,
    HardwareComponent,
    I2CDeviceMap,
    PowerSpecification,
    RaspberryPiModel,
    UARTAssignment,
)
from .log_bundle import LogBundle
from .motor_control import (
    BladeCommand,
    ControlMode,
    DriveCommand,
    DriveController,
    EncoderFeedback,
    MotorControl,
    MotorDiagnostics,
    MotorStatus,
)
from .navigation_state import (
    CoverageCell,
    NavigationMode,
    NavigationState,
    Obstacle,
    PathStatus,
    Position,
    Waypoint,
)
from .navigation_waypoint import NavigationWaypoint
from .operational_data import (
    EventType,
    JobExecution,
    MaintenanceRecord,
    OperationalData,
    OperationalEvent,
    OperationStatus,
    PerformanceMetrics,
    Severity,
    SystemHealth,
)
from .power_management import (
    BatteryChemistry,
    BatteryStatus,
    ChargingStatus,
    INA3221Reading,
    PowerBudget,
    PowerManagement,
    PowerMode,
    SolarStatus,
)
from .scheduled_job import JobState, RetryPolicy, ScheduledJob
from .sensor_data import (
    EnvironmentalReading,
    GpsMode,
    GpsReading,
    ImuReading,
    PowerReading,
    SensorData,
    SensorReading,
    SensorStatus,
    SensorType,
    TofReading,
)
from .sensor_reading import SensorReadingV2
from .system_configuration import (
    AIRunnerPreference,
    AISettings,
    BrandingReference,
    CameraSettings,
    ControlSettings,
    DriveControllerConfig,
    GpsModeConfig,
    LogLevel,
    MapsSettings,
    NavigationSettings,
    NetworkConfiguration,
    OperationalMode,
    SafetyThresholds,
    SensorCalibration,
    SettingsProfile,
    SystemConfiguration,
    SystemSettings,
    TelemetrySettings,
    UIPreferences,
)
from .telemetry_exchange import (
    ClientSubscription,
    ComponentId,
    ComponentStatus,
    GPSData,
    HardwareTelemetryStream,
    IMUData,
    MessagePriority,
    MotorData,
    PowerData,
    RtkFixType,
    StreamConfiguration,
    StreamStatistics,
    StreamStatus,
    TelemetryExchange,
    TelemetryHub,
    TelemetryMessage,
    TelemetryTopic,
    ToFData,
)
from .training_data import (
    AnnotationType,
    BoundingBoxAnnotation,
    DatasetExport,
    DatasetFormat,
    DatasetStatistics,
    LabelStatus,
    ObjectAnnotation,
    TrainingData,
    TrainingImage,
)
from .user_session import (
    AuthenticationMethod,
    ConnectionType,
    Permission,
    SecurityContext,
    SessionActivity,
    SessionStatus,
    UserPreferences,
    UserRole,
    UserSession,
    WebSocketConnection,
)
from .verification_artifact import (
    ArtifactType,
    PlatformInfo,
    TelemetrySnapshot,
    VerificationArtifact,
    VerificationArtifactCollection,
)
from .verification_artifact import (
    PerformanceMetrics as VerificationPerformanceMetrics,
)
from .webui_contracts import (
    AuthRequirement,
    DataDependency,
    DataDependencyType,
    DocumentationBundle,
    DocumentationFile,
    DocumentationType,
    PerformanceMetrics,
    TelemetryRequirement,
    WebUIPageContract,
    WebUIPageContracts,
    WebUIPageSlug,
)
from .zone import (
    MapConfiguration,
    MapMarker,
    MapProvider,
    MarkerSchedule,
    MarkerTimeWindow,
    MarkerTriggerSet,
    MarkerType,
    Point,
    Zone,
    ZoneSettings,
    ZoneStatistics,
    ZoneType,
)

__all__ = [
    # Sensor Data
    "SensorData",
    "SensorReading",
    "GpsReading",
    "ImuReading",
    "TofReading",
    "EnvironmentalReading",
    "PowerReading",
    "SensorType",
    "SensorStatus",
    "GpsMode",
    # Navigation
    "NavigationState",
    "Position",
    "Waypoint",
    "Obstacle",
    "CoverageCell",
    "NavigationMode",
    "PathStatus",
    # Motor Control
    "MotorControl",
    "DriveCommand",
    "BladeCommand",
    "EncoderFeedback",
    "MotorDiagnostics",
    "DriveController",
    "ControlMode",
    "MotorStatus",
    # Power Management
    "PowerManagement",
    "BatteryStatus",
    "SolarStatus",
    "INA3221Reading",
    "PowerBudget",
    "PowerMode",
    "BatteryChemistry",
    "ChargingStatus",
    # Camera Stream
    "CameraStream",
    "CameraFrame",
    "FrameMetadata",
    "StreamStatistics",
    "CameraConfiguration",
    "CameraMode",
    "FrameFormat",
    "StreamQuality",
    "CameraCapabilities",
    # AI Processing
    "AIProcessing",
    "InferenceResult",
    "DetectedObject",
    "ModelInfo",
    "AcceleratorStatus",
    "AIAccelerator",
    "ModelFormat",
    "InferenceTask",
    "ModelStatus",
    "BoundingBox",
    # Training Data
    "TrainingData",
    "TrainingImage",
    "ObjectAnnotation",
    "DatasetStatistics",
    "DatasetExport",
    "DatasetFormat",
    "LabelStatus",
    "AnnotationType",
    "BoundingBoxAnnotation",
    # WebUI Contracts
    "WebUIPageContracts",
    "WebUIPageContract",
    "DataDependency",
    "TelemetryRequirement",
    "WebUIPageSlug",
    "AuthRequirement",
    "DataDependencyType",
    "PerformanceMetrics",
    "DocumentationBundle",
    "DocumentationFile",
    "DocumentationType",
    # Telemetry Exchange
    "TelemetryExchange",
    "TelemetryHub",
    "TelemetryMessage",
    "StreamConfiguration",
    "ClientSubscription",
    "StreamStatistics",
    "TelemetryTopic",
    "MessagePriority",
    "StreamStatus",
    "HardwareTelemetryStream",
    "ComponentId",
    "ComponentStatus",
    "RtkFixType",
    "GPSData",
    "IMUData",
    "MotorData",
    "PowerData",
    "ToFData",
    # Zones and Map Configuration
    "Zone",
    "ZoneType",
    "Point",
    "ZoneSettings",
    "ZoneStatistics",
    "MarkerSchedule",
    "MarkerTimeWindow",
    "MarkerTriggerSet",
    "MapConfiguration",
    "MapMarker",
    "MarkerType",
    "MapProvider",
    # Control Session
    "ControlSession",
    "ControlCommand",
    "ControlAuditEntry",
    "EmergencyState",
    "ControlCommandType",
    "ControlCommandResult",
    "EmergencyStatus",
    "SafetyInterlock",
    # User Session
    "UserSession",
    "SessionActivity",
    "UserPreferences",
    "SecurityContext",
    "WebSocketConnection",
    "SessionStatus",
    "UserRole",
    "AuthenticationMethod",
    "ConnectionType",
    "Permission",
    # Hardware Baseline
    "HardwareBaseline",
    "HardwareComponent",
    "GPIOPinAssignment",
    "I2CDeviceMap",
    "UARTAssignment",
    "PowerSpecification",
    "RaspberryPiModel",
    "GpsModuleType",
    "DriveControllerType",
    "AIAcceleratorType",
    "ComponentStatus",
    # System Configuration
    "SystemConfiguration",
    "SensorCalibration",
    "NavigationSettings",
    "SafetyThresholds",
    "UIPreferences",
    "BrandingReference",
    "NetworkConfiguration",
    "OperationalMode",
    "GpsModeConfig",
    "DriveControllerConfig",
    "AIRunnerPreference",
    "LogLevel",
    "SettingsProfile",
    "TelemetrySettings",
    "ControlSettings",
    "MapsSettings",
    "CameraSettings",
    "AISettings",
    "SystemSettings",
    # Operational Data
    "OperationalData",
    "OperationalEvent",
    "PerformanceMetrics",
    "MaintenanceRecord",
    "JobExecution",
    "SystemHealth",
    "OperationStatus",
    "EventType",
    "Severity",
    # Verification Artifacts
    "VerificationArtifact",
    "VerificationArtifactCollection",
    "ArtifactType",
    "PlatformInfo",
    "VerificationPerformanceMetrics",
    "TelemetrySnapshot",
]

# Additional exports for Phase 4/6/7 models
__all__ += [
    "NavigationWaypoint",
    "SensorReadingV2",
    "Geofence",
    "LatLng",
    "ScheduledJob",
    "JobState",
    "RetryPolicy",
    "CoveragePattern",
    "LogBundle",
]
