"""Replay-parity integration test.

Loads the committed golden fixture, replays each captured SensorData through a
fresh NavigationService, and asserts the produced state matches the recorded
state. A failure here means navigation behavior has drifted from the fixture —
either an intentional change (regenerate the fixture) or a regression
(fix the code).

Tolerances are zero: the fixture was generated by the same code path the test
replays through, with deterministic inputs and no clock drift, so parity must
be exact. A non-zero delta means a real behavior change. If a real-yard
fixture is added in the future, that fixture's test may need looser tolerances
because of GPS noise — but the synthetic fixture's contract is exact match.
"""
from __future__ import annotations

from pathlib import Path

import pytest

from backend.src.diagnostics.replay import ReplayLoader
from backend.src.services.navigation_service import NavigationService

FIXTURE = (
    Path(__file__).resolve().parents[1]
    / "fixtures"
    / "navigation"
    / "synthetic_straight_drive.jsonl"
)

# Zero tolerances: fixture and current code path are the same code, so any
# non-zero numeric delta indicates a real behavior change.
HEADING_TOL_DEG = 0.0
LATLON_TOL = 0.0
VELOCITY_TOL_MPS = 0.0


@pytest.mark.asyncio
async def test_synthetic_straight_drive_replays_with_parity():
    assert FIXTURE.exists(), f"missing golden fixture: {FIXTURE}"

    # Reuse one NavigationService across all records to mirror the fixture's
    # generation path. Session state (GPS COG history, dead reckoning,
    # waypoint index) accumulates across update_navigation_state calls; a
    # fresh-per-record approach would diverge from the fixture.
    nav = NavigationService()

    deltas: list[str] = []
    step = 0
    for record in ReplayLoader(FIXTURE):
        result = await nav.update_navigation_state(record.sensor_data)
        expected = record.navigation_state_after

        # Heading
        if expected.heading is not None and result.heading is not None:
            d = abs(result.heading - expected.heading)
            if d > HEADING_TOL_DEG:
                deltas.append(
                    f"step {step} heading: got {result.heading:.6f} deg, "
                    f"expected {expected.heading:.6f} deg, delta={d:.6f}"
                )
        elif expected.heading != result.heading:
            deltas.append(
                f"step {step} heading nullness mismatch: "
                f"got {result.heading}, expected {expected.heading}"
            )

        # Position
        if expected.current_position is not None and result.current_position is not None:
            dlat = abs(result.current_position.latitude - expected.current_position.latitude)
            dlon = abs(result.current_position.longitude - expected.current_position.longitude)
            if dlat > LATLON_TOL or dlon > LATLON_TOL:
                deltas.append(
                    f"step {step} position: dlat={dlat:.3e}, dlon={dlon:.3e}, "
                    f"got ({result.current_position.latitude:.9f},"
                    f"{result.current_position.longitude:.9f}), "
                    f"expected ({expected.current_position.latitude:.9f},"
                    f"{expected.current_position.longitude:.9f})"
                )
        elif (expected.current_position is None) != (result.current_position is None):
            deltas.append(
                f"step {step} position nullness mismatch: "
                f"got {result.current_position}, expected {expected.current_position}"
            )

        # Velocity
        if expected.velocity is not None and result.velocity is not None:
            d = abs(result.velocity - expected.velocity)
            if d > VELOCITY_TOL_MPS:
                deltas.append(
                    f"step {step} velocity: got {result.velocity:.6f} m/s, "
                    f"expected {expected.velocity:.6f} m/s, delta={d:.6f}"
                )
        elif (expected.velocity is None) != (result.velocity is None):
            deltas.append(
                f"step {step} velocity nullness mismatch: "
                f"got {result.velocity}, expected {expected.velocity}"
            )

        step += 1

    assert step == 5, f"expected 5 fixture records, got {step}"
    assert not deltas, "Replay parity broke:\n" + "\n".join(deltas)
