# Pre-commit hooks configuration for LawnBerry Pi v2
# Constitutional compliance: Code Quality Gates with ruff, black, mypy

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--strict, --ignore-missing-imports]

  - repo: local
    hooks:
      - id: constitutional-compliance
        name: Constitutional compliance check
        entry: python -c "import platform, sys; assert platform.system() == 'Linux' and platform.machine() == 'aarch64', 'ARM64 Linux required'; assert sys.version_info >= (3, 11), 'Python 3.11+ required'"
        language: system
        pass_filenames: false

      - id: forbidden-packages
        name: Check for forbidden packages
        entry: bash -c "if grep -r 'import.*\(pycoral\|edgetpu\)' src/ || grep -r 'from.*\(pycoral\|edgetpu\)' src/; then echo 'ERROR: pycoral/edgetpu forbidden in main environment (use Coral isolated venv)'; exit 1; fi"
        language: system
        pass_filenames: false

      - id: todo-check
        name: TODO format validation
        entry: bash -c "if grep -rn 'TODO[^(]' src/ tests/ docs/; then echo 'ERROR: Unlinked TODOs found. Use TODO(v3): format with GitHub issue links'; exit 1; fi"
        language: system
        pass_filenames: false