# Data Management Configuration
# Redis-based caching and SQLite persistence with analytics

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  
  # Cache TTL settings (seconds)
  default_ttl: 300        # 5 minutes
  sensor_ttl: 60          # 1 minute for sensor data
  config_ttl: 3600        # 1 hour for configuration
  state_ttl: 30           # 30 seconds for operational state
  
  # Connection pool settings
  max_connections: 20
  retry_on_timeout: true

database:
  path: "/var/lib/lawnberry/data.db"
  
  # Performance settings
  batch_size: 1000
  vacuum_interval_days: 7
  
  # Data retention policies (days)
  retention_policies:
    sensor_readings: 30
    navigation_data: 14
    operational_logs: 60
    performance_metrics: 90
    operational_states: 7

state_management:
  # State persistence settings
  persist_interval: 5     # seconds
  max_history: 100        # state transitions to keep
  
  # Recovery settings
  recovery_timeout: 30    # seconds
  checkpoint_retention: 7 # days

analytics:
  # Analysis windows
  analysis_window_hours: 24
  trend_window_days: 7
  
  # Real-time analytics
  analytics_interval: 60  # seconds
  buffer_sizes:
    sensor_data: 1000
    performance_data: 500
  
  # Performance thresholds
  thresholds:
    battery_efficiency: 0.8
    coverage_rate: 0.9
    navigation_accuracy: 0.95
    sensor_reliability: 0.98
    response_time_ms: 10    # Target <10ms for cache operations

backup:
  backup_path: "/var/backups/lawnberry"
  
  # Backup schedule
  daily_backup: true
  backup_retention_days: 30
  
  # Export settings
  max_export_records: 100000
  supported_formats: ["json", "csv"]

performance:
  # Response time targets (milliseconds)
  cache_target_ms: 10
  database_target_ms: 100
  analytics_target_ms: 500
  
  # Resource limits
  max_memory_mb: 512
  max_cache_size_mb: 128
  
  # Monitoring
  performance_logging: true
  slow_query_threshold_ms: 100

logging:
  level: "INFO"
  performance_logging: true
  analytics_logging: true
  
  log_files:
    main: "/var/log/lawnberry/data_management.log"
    performance: "/var/log/lawnberry/data_performance.log"
    analytics: "/var/log/lawnberry/analytics.log"

# Data lifecycle management
lifecycle:
  # Automatic cleanup
  cleanup_interval_hours: 1
  cleanup_batch_size: 1000
  
  # Data archival
  archive_old_data: true
  archive_threshold_days: 90
  
  # Privacy and GDPR compliance
  anonymize_old_data: false
  data_retention_policy: "30_days_operational_90_days_analytics"

# Integration settings
integration:
  # MQTT bridge for real-time data distribution
  mqtt_bridge: true
  mqtt_topics:
    sensor_data: "lawnberry/data/sensors"
    state_updates: "lawnberry/data/state"
    analytics: "lawnberry/data/analytics"
    alerts: "lawnberry/data/alerts"
  
  # External system integration
  export_api: true
  webhook_notifications: false

# Security settings
security:
  encrypt_sensitive_data: false
  data_anonymization: false
  audit_logging: true
  
  # Access control
  require_authentication: false
  api_rate_limiting: true
  rate_limit_requests_per_minute: 1000
