# Deployment Automation Configuration
# Configuration for automated deployment system with A/B deployment and security updates

deployment:
  # Update server configuration
  update_server_url: "https://updates.lawnberry.com/api/v1"
  update_check_interval: 3600  # Check every hour
  
  # Automatic deployment settings
  security_update_priority: true
  auto_deploy_security: true
  auto_deploy_bug_fixes: true
  auto_deploy_features: false
  auto_deploy_configuration: true
  
  # Deployment timeouts and limits
  health_check_timeout: 300  # 5 minutes
  deployment_timeout: 1800   # 30 minutes
  rollback_timeout: 300      # 5 minutes
  max_retry_attempts: 3
  
  # A/B deployment configuration
  ab_deployment:
    enabled: true
    health_check_delay: 10    # Seconds to wait before health check
    stability_period: 60      # Seconds to monitor before marking stable
    rollback_on_failure: true
    
  # Fleet management
  fleet:
    enabled: false
    group_id: "default"
    deployment_wave: 1        # Deployment wave (1-5, 1=earliest)
    max_concurrent_deployments: 1
    
  # Backup and recovery
  backup:
    enabled: true
    retention_days: 30
    max_backups: 10
    compress_backups: true
    
  # Security settings
  security:
    verify_signatures: true
    verify_checksums: true
    require_https: true
    certificate_validation: true
    
  # Monitoring and alerting
  monitoring:
    log_deployments: true
    send_notifications: true
    track_metrics: true
    alert_on_failure: true
    
  # System paths
  paths:
    deployment_dir: "/opt/lawnberry/deployments"
    backup_dir: "/var/lib/lawnberry/backups"
    staging_dir: "/tmp/lawnberry_staging"
    key_dir: "/opt/lawnberry/keys"
    
  # Package validation
  validation:
    required_files:
      - "src/system_integration/system_manager.py"
      - "src/hardware/__init__.py"
      - "src/safety/__init__.py"
      - "config/system.yaml"
    max_package_size: 100000000  # 100MB
    allowed_extensions: [".tar.gz", ".zip"]
    
  # Performance settings
  performance:
    download_chunk_size: 8192
    max_download_bandwidth: 0  # 0 = unlimited
    parallel_downloads: false
    
  # Emergency settings
  emergency:
    override_auto_deploy: true
    skip_health_checks: false
    force_immediate_deploy: true
    emergency_contact_url: ""
