# Field Testing Configuration for LawnBerry System
# Comprehensive controlled environment testing parameters

test_environment:
  # Test area specifications
  max_test_area_sqm: 1000
  min_test_duration_hours: 2
  max_test_duration_hours: 24
  safety_perimeter_m: 5
  
  # Observer positions for monitoring
  observer_positions:
    - x: 0
      y: 0
      description: "Control station - main monitoring point"
    - x: 20
      y: 20
      description: "Corner observer - boundary monitoring"
    - x: -20
      y: 20
      description: "Safety observer - emergency response"
  
  # Test environment setup requirements
  required_equipment:
    - "Emergency stop remote control"
    - "Video recording equipment"
    - "Safety barriers and markers"
    - "Communication equipment"
    - "First aid kit"
    - "Test obstacles (cones, barriers)"
    - "Weather monitoring equipment"
  
  # Environmental conditions for testing
  acceptable_weather:
    min_temperature_c: 5
    max_temperature_c: 35
    max_wind_speed_ms: 8
    max_precipitation_mm_h: 2
    min_visibility_m: 50

safety_testing:
  # Emergency stop functionality tests
  emergency_stop_tests:
    - "physical_button"       # Hardware emergency button
    - "remote_command"        # Remote control emergency stop
    - "web_interface"         # Web dashboard emergency stop
    - "automatic_detection"   # System-triggered emergency stop
    - "communication_loss"    # Emergency stop on comm failure
  
  # Obstacle detection scenarios
  obstacle_scenarios:
    - "stationary_object"     # Static obstacles (rocks, toys)
    - "moving_person"         # Human walking in path
    - "moving_pet"           # Pet/animal movement
    - "unexpected_barrier"    # Sudden barrier appearance
    - "low_obstacle"         # Ground-level obstacles
    - "reflective_surface"   # Mirrors, glass surfaces
  
  # Boundary enforcement tests
  boundary_tests:
    - "gps_boundary"         # GPS-defined boundaries
    - "physical_boundary"    # Physical barriers
    - "no_go_zones"         # Designated no-go areas
    - "slope_boundaries"     # Terrain-based boundaries
    - "water_boundaries"     # Water feature boundaries
  
  # Weather condition testing
  weather_scenarios:
    - "light_rain"           # Light precipitation
    - "strong_wind"          # High wind conditions
    - "temperature_extreme"   # Hot/cold temperature limits
    - "humidity_extreme"     # High humidity conditions
    - "dawn_dusk"           # Low light conditions
  
  # System recovery testing
  recovery_scenarios:
    - "power_loss_recovery"  # Recovery from power interruption
    - "communication_recovery" # Recovery from network loss
    - "sensor_failure_recovery" # Recovery from sensor failures
    - "stuck_recovery"       # Recovery from being stuck
    - "tilt_recovery"        # Recovery from excessive tilt

# Performance targets and thresholds
performance_targets:
  # Mowing performance
  mowing_efficiency_min: 85.0      # Minimum mowing efficiency %
  coverage_quality_min: 95.0       # Minimum coverage quality %
  pattern_accuracy_min: 90.0       # Pattern following accuracy %
  
  # Power and battery
  battery_life_min_hours: 4.0      # Minimum battery life
  charging_efficiency_min: 85.0    # Minimum charging efficiency %
  solar_efficiency_min: 75.0       # Minimum solar charging efficiency %
  
  # Navigation and positioning
  gps_accuracy_max_meters: 0.5     # Maximum GPS error
  boundary_accuracy_max_meters: 0.3 # Maximum boundary deviation
  obstacle_detection_accuracy_min: 98.0 # Minimum obstacle detection rate
  
  # Safety and response
  safety_response_max_ms: 200      # Maximum safety response time
  emergency_stop_max_ms: 100       # Maximum emergency stop time
  communication_timeout_max_s: 30   # Maximum communication timeout
  
  # System performance
  system_uptime_min_percent: 99.0  # Minimum system uptime
  memory_usage_max_mb: 2048        # Maximum memory usage
  cpu_usage_max_percent: 80        # Maximum CPU usage
  temperature_max_c: 70            # Maximum operating temperature
  
  # Environmental impact
  noise_level_max_db: 65           # Maximum noise level
  vibration_max_g: 2.0            # Maximum vibration level

# Data collection and monitoring
data_collection:
  # Metrics collection
  metrics_interval_seconds: 30     # How often to collect metrics
  detailed_logging: true           # Enable detailed logging
  video_recording: true            # Record test sessions
  sensor_logging: true             # Log all sensor data
  performance_profiling: true      # Enable performance profiling
  
  # User observation and feedback
  user_observation_notes: true     # Collect observer notes
  photo_documentation: true        # Photo documentation of tests
  incident_reporting: true         # Detailed incident reports
  
  # Data storage
  max_log_size_mb: 1000           # Maximum log file size
  log_retention_days: 90          # How long to keep logs
  backup_test_data: true          # Backup test data
  
  # Real-time monitoring
  realtime_dashboard: true        # Enable real-time monitoring
  alert_thresholds: true          # Enable threshold-based alerts
  remote_monitoring: true         # Enable remote monitoring

# Test scenarios and workflows
test_scenarios:
  # Basic functionality tests (30 minutes)
  basic_functionality:
    duration_minutes: 30
    test_area_sqm: 100
    required_tests:
      - "system_startup"
      - "basic_navigation"
      - "simple_mowing_pattern"
      - "emergency_stop"
      - "system_shutdown"
  
  # Safety validation tests (60 minutes)
  safety_validation:
    duration_minutes: 60
    test_area_sqm: 200
    required_tests:
      - "all_emergency_stops"
      - "obstacle_detection_suite"
      - "boundary_enforcement"
      - "weather_safety"
      - "recovery_procedures"
  
  # Performance benchmarking (4 hours)
  performance_benchmark:
    duration_minutes: 240
    test_area_sqm: 500
    required_tests:
      - "mowing_efficiency"
      - "battery_life"
      - "gps_accuracy"
      - "pattern_execution"
      - "system_stability"
  
  # Extended operation test (24 hours)
  extended_operation:
    duration_minutes: 1440
    test_area_sqm: 1000
    required_tests:
      - "continuous_operation"
      - "multiple_charge_cycles"
      - "weather_adaptation"
      - "long_term_stability"
      - "maintenance_intervals"
  
  # Stress testing (2 hours)
  stress_test:
    duration_minutes: 120
    test_area_sqm: 300
    required_tests:
      - "maximum_load"
      - "extreme_conditions"
      - "rapid_pattern_changes"
      - "communication_stress"
      - "concurrent_operations"

# Reporting and documentation
reporting:
  # Report generation
  generate_detailed_reports: true  # Generate comprehensive reports
  include_photos_videos: true      # Include media in reports
  performance_charts: true         # Generate performance charts
  comparison_analysis: true        # Compare with previous tests
  
  # Report formats
  json_reports: true              # JSON format reports
  csv_data_export: true           # CSV data for analysis
  pdf_summary: true               # PDF executive summary
  html_dashboard: true            # HTML dashboard reports
  
  # Distribution
  email_reports: false            # Email reports (requires config)
  upload_to_cloud: false          # Cloud storage (requires config)
  local_archive: true             # Local report archiving
  
  # Compliance documentation
  safety_certification: true      # Safety compliance documentation
  performance_certification: true # Performance compliance docs
  regulatory_compliance: true     # Regulatory compliance docs

# Quality assurance
quality_assurance:
  # Test validation
  require_witness: true           # Require test witness
  double_check_critical: true     # Double-check critical tests
  photo_verification: true        # Photo verification of tests
  
  # Data integrity
  checksum_validation: true       # Validate data integrity
  backup_verification: true       # Verify backup integrity
  audit_trail: true              # Maintain audit trail
  
  # Compliance checking
  automatic_compliance_check: true # Auto-check compliance
  manual_review_required: true    # Require manual review
  approval_workflow: true         # Approval workflow for results

# Communication and alerting
communication:
  # Real-time alerts
  critical_alert_phone: false     # Phone alerts (requires config)
  critical_alert_email: false     # Email alerts (requires config)
  dashboard_alerts: true          # Dashboard alert system
  
  # Status updates
  progress_notifications: true    # Test progress notifications
  completion_notifications: true  # Test completion notifications
  failure_notifications: true     # Immediate failure notifications
  
  # Documentation
  test_log_sharing: true          # Share test logs
  photo_sharing: true             # Share photos/videos
  report_distribution: true       # Distribute final reports

# Advanced testing features
advanced_features:
  # AI and machine learning testing
  ml_model_validation: true       # Test ML models
  ai_decision_testing: true       # Test AI decision making
  learning_adaptation_test: true  # Test adaptive learning
  
  # Integration testing
  multi_system_integration: true  # Test system integration
  third_party_integration: true   # Test 3rd party integrations
  api_stress_testing: true        # Test API performance
  
  # Simulation and modeling
  scenario_simulation: true       # Simulate complex scenarios
  weather_simulation: false       # Weather simulation (requires hardware)
  terrain_modeling: true          # Test terrain adaptation
  
  # Future compatibility
  firmware_update_testing: true   # Test firmware updates
  backward_compatibility: true    # Test backward compatibility
  migration_testing: true         # Test system migrations
