# ML Obstacle Detection System Configuration

# Core ML Detection Settings
ml_detection:
  enabled: true
  model_ensemble_enabled: true
  temporal_filtering_enabled: true
  motion_tracking_enabled: true
  trajectory_prediction_enabled: true
  
  # Performance Targets
  performance_targets:
    accuracy: 0.95                    # >95% accuracy requirement
    false_positive_rate: 0.05         # <5% false positive rate requirement
    latency_ms: 100.0                 # <100ms processing time requirement
    availability: 0.99                # 99% system availability
  
  # Detection Thresholds
  confidence_threshold: 0.6           # Base confidence threshold
  safety_confidence_boost: 0.1        # Boost for safety-critical objects
  motion_detection_threshold: 5.0     # Pixels/frame for motion detection
  
  # Model Configuration
  models:
    primary_weight: 0.6               # Weight for primary model
    backup_weight: 0.3                # Weight for backup model  
    motion_weight: 0.1                # Weight for motion-specific model
    
    ensemble_fusion_threshold: 0.3    # IoU threshold for detection fusion
    model_switching_enabled: true     # Enable dynamic model switching
    
  # Temporal Filtering
  temporal_filter:
    history_length: 10                # Number of detections to track
    confirmation_threshold: 2         # Confirmations needed for detection
    consistency_threshold: 0.3        # Max std dev for consistent detection
    false_positive_suppression: true  # Enable FP suppression
    
  # Motion and Trajectory
  motion_tracking:
    optical_flow_enabled: true
    kalman_filter_enabled: true
    prediction_horizon_seconds: 2.0
    motion_vector_smoothing: 0.7
    
  # Real-time Processing
  processing:
    parallel_inference: true
    frame_queue_size: 5
    result_queue_size: 10
    processing_thread_priority: "high"

# Adaptive Learning System
adaptive_learning:
  enabled: true
  online_learning: true
  environment_adaptation: true
  user_feedback_integration: true
  
  # Learning Configuration
  learning_params:
    min_examples_for_training: 100
    retraining_threshold: 500
    adaptation_threshold: 0.1
    confidence_adjustment_rate: 0.05
    temporal_decay_factor: 0.95
    max_training_examples: 10000
    
  # Environment Adaptation
  environment_adaptation:
    enabled: true
    context_weight: 0.3
    adaptation_trigger_threshold: 0.1
    min_adaptation_interval_seconds: 300
    environment_change_sensitivity: 0.2
    
  # User Feedback
  user_feedback:
    enabled: true
    feedback_weight: 0.5
    user_expertise_decay: 0.9
    immediate_adjustment_threshold: 0.8
    feedback_validation_enabled: true
    
  # Data Management
  data_management:
    training_data_retention_days: 30
    model_backup_enabled: true 
    data_compression_enabled: true
    privacy_anonymization: true

# Safety Integration
safety_integration:
  enabled: true
  graduated_response: true
  manual_override_support: true
  false_positive_suppression: true
  
  # Response Configuration
  response_levels:
    emergency_stop:
      objects: ["person", "child"]
      max_distance: 4.5
      response_time_ms: 50
      retry_attempts: 0
      
    stop_and_assess:
      objects: ["pet", "dog", "cat", "toy"]
      max_distance: 2.0  
      response_time_ms: 200
      retry_attempts: 3
      escalation_time_seconds: 5
      
    slow_down:
      objects: ["moving_object", "unknown"]
      max_distance: 1.0
      response_time_ms: 300
      retry_attempts: 3
      escalation_time_seconds: 8
      
    continue:
      objects: ["static_object", "vegetation"]
      max_distance: 0.5
      response_time_ms: 0
      retry_attempts: 0
  
  # Safety Overrides
  manual_override:
    enabled: true
    max_duration_seconds: 1800        # 30 minutes maximum
    auto_expire: true
    emergency_disable_override: true
    
  # False Positive Handling
  false_positive_handling:
    suppression_enabled: true
    suppression_duration_hours: 24
    user_reporting_enabled: true
    automatic_detection_enabled: true

# System Integration
system_integration:
  existing_system_integration: true
  tof_sensor_fusion: true
  gps_integration: true
  imu_integration: true
  
  # Communication
  mqtt_integration:
    detection_results_topic: "lawnberry/ml_detection/results"
    safety_alerts_topic: "lawnberry/safety/ml_alert"
    learning_feedback_topic: "lawnberry/learning/feedback"
    health_status_topic: "lawnberry/ml_detection/health_status"
    performance_metrics_topic: "lawnberry/ml_detection/performance"
    
  # Data Flow
  data_flow:
    camera_frame_topic: "lawnberry/vision/camera_frame"
    sensor_fusion_topic: "lawnberry/sensors/fusion_result"
    navigation_command_topic: "lawnberry/navigation/ml_command"
    
# Monitoring and Diagnostics
monitoring:
  enabled: true
  performance_monitoring: true
  health_checks: true
  automated_alerts: true
  
  # Health Check Configuration
  health_checks:
    interval_seconds: 30
    timeout_seconds: 5
    failure_threshold: 3
    recovery_threshold: 2
    
    # Component Health Checks
    components:
      ml_detector: true
      learning_system: true
      safety_integration: true
      model_ensemble: true
      
  # Performance Monitoring
  performance_monitoring:
    metrics_collection: true
    real_time_alerts: true
    trend_analysis: true
    automated_reporting: true
    
    # Metrics Configuration
    metrics:
      accuracy_tracking: true
      latency_tracking: true
      false_positive_tracking: true
      throughput_tracking: true
      resource_usage_tracking: true
      
  # Alerting
  alerting:
    performance_degradation: true
    system_errors: true
    safety_violations: true
    learning_anomalies: true
    
    # Alert Thresholds
    thresholds:
      accuracy_drop_threshold: 0.05   # 5% accuracy drop triggers alert
      latency_spike_threshold: 50.0   # 50ms latency increase triggers alert
      false_positive_spike_threshold: 0.03  # 3% FP rate increase triggers alert
      error_rate_threshold: 0.01      # 1% error rate triggers alert

# Resource Management
resource_management:
  memory_management: true
  cpu_optimization: true
  storage_management: true
  
  # Memory Configuration
  memory:
    max_usage_mb: 512
    garbage_collection_threshold: 0.8
    memory_pool_enabled: true
    cache_optimization: true
    
  # CPU Configuration  
  cpu:
    max_usage_percent: 80.0
    thread_pool_size: 4
    priority_scheduling: true
    affinity_enabled: true
    
  # Storage Configuration
  storage:
    max_training_data_gb: 5.0
    model_compression: true
    data_archival_enabled: true
    cleanup_interval_hours: 24

# Development and Testing
development:
  debug_mode: false
  test_mode: false
  simulation_mode: false
  profiling_enabled: false
  
  # Testing Configuration
  testing:
    unit_tests_enabled: true
    integration_tests_enabled: true
    performance_tests_enabled: true
    safety_tests_enabled: true
    
    # Test Data
    test_data:
      synthetic_data_generation: true
      test_scenarios_enabled: true
      edge_case_testing: true
      stress_testing: true
      
  # Debugging
  debugging:
    verbose_logging: false
    trace_enabled: false
    metrics_export: true
    diagnostic_dumps: false

# Security and Privacy
security:
  data_encryption: true
  access_control: true
  audit_logging: true
  privacy_protection: true
  
  # Data Protection
  data_protection:
    training_data_encryption: true
    model_encryption: true
    communication_encryption: true
    local_storage_encryption: true
    
  # Access Control
  access_control:
    user_authentication: true
    role_based_access: true
    api_key_authentication: true
    session_management: true
    
  # Privacy
  privacy:
    data_anonymization: true
    personal_data_detection: true
    consent_management: true
    data_retention_policies: true

# Logging Configuration
logging:
  level: "INFO"
  file_logging: true
  console_logging: true
  structured_logging: true
  
  # Log Categories
  categories:
    detection: true
    learning: true
    safety: true
    performance: true
    errors: true
    
  # Log Rotation
  rotation:
    max_file_size_mb: 50
    max_files: 10
    rotation_interval_hours: 24
    compression_enabled: true
