# Power Management System Configuration

# Battery Configuration
battery:
  # Battery specifications
  type: "LiFePO4"
  nominal_voltage: 12.8  # V
  capacity_ah: 30.0      # Ah
  max_charge_voltage: 14.6  # V
  min_discharge_voltage: 10.0  # V
  float_voltage: 13.6    # V
  
  # Safety thresholds (as fractions 0.0-1.0)
  thresholds:
    critical_level: 0.05   # 5% - Emergency shutdown
    low_level: 0.20        # 20% - Navigate to sunny spot
    optimal_level: 0.80    # 80% - Full performance mode
    
  # Temperature limits
  temperature:
    max_operating: 60.0    # °C
    min_operating: -20.0   # °C
    max_charging: 45.0     # °C
    min_charging: 0.0      # °C

# Solar Panel Configuration
solar:
  # Panel specifications
  max_power: 30.0          # W
  nominal_voltage: 14.0    # V
  panel_efficiency: 0.20   # 20% efficiency
  
  # MPPT Controller
  mppt:
    enabled: true
    max_current: 20.0      # A
    efficiency: 0.95       # 95% conversion efficiency
  
  # Solar estimation
  estimation:
    daylight_hours:
      start: 6             # Hour when solar starts
      end: 20              # Hour when solar ends
    peak_hour: 12          # Hour of peak solar
    cloud_impact_factor: 0.8  # How much clouds reduce efficiency
    seasonal_variation: true  # Enable seasonal adjustments

# Power Monitoring Configuration
monitoring:
  # Update intervals (seconds)
  intervals:
    battery_monitoring: 5.0    # Battery data update rate
    solar_monitoring: 5.0      # Solar data update rate
    power_optimization: 30.0   # Power mode optimization
    sunny_spot_update: 300.0   # Sunny spot learning rate
    
  # Data retention
  retention:
    battery_history: 1000      # Number of readings to keep
    solar_history: 1000        # Number of readings to keep
    consumption_history: 1000  # Number of readings to keep
  
  # INA3221 Power Monitor
  ina3221:
    i2c_address: 0x40
    channel: 1               # Battery monitoring channel
    shunt_resistance: 0.1    # Ohms
    max_current: 5.0         # A

# Power Modes Configuration
power_modes:
  # High Performance Mode
  high_performance:
    cpu_governor: "performance"
    sensor_rates:
      tof_sensors: 10.0      # Hz
      environmental: 1.0     # Hz
      gps: 5.0              # Hz
      imu: 50.0             # Hz
    camera:
      resolution: "1080p"
      fps: 30
    enabled_sensors: "all"
  
  # Eco Mode
  eco_mode:
    cpu_governor: "ondemand"
    sensor_rates:
      tof_sensors: 2.0       # Hz
      environmental: 0.1     # Hz (every 10 seconds)
      gps: 1.0              # Hz
      imu: 10.0             # Hz
    camera:
      resolution: "720p"
      fps: 15
    enabled_sensors: "essential"
  
  # Charging Mode
  charging_mode:
    cpu_governor: "ondemand"
    sensor_rates:
      tof_sensors: 1.0       # Hz
      environmental: 0.1     # Hz
      gps: 1.0              # Hz
      imu: 5.0              # Hz
    camera:
      enabled: false
    enabled_sensors: "critical"
  
  # Emergency Mode
  emergency_mode:
    cpu_governor: "powersave"
    sensor_rates:
      tof_sensors: 0.5       # Hz
      environmental: 0.05    # Hz (every 20 seconds)
      gps: 0.5              # Hz
      imu: 1.0              # Hz
    camera:
      enabled: false
    enabled_sensors: "minimal"

# Power Consumption Estimates (Watts)
power_consumption:
  base_components:
    cpu_base: 2.0            # Base CPU power
    cpu_scaling: 3.0         # Additional power per performance step
    sensor_power: 0.5        # Power per active sensor
    camera_power: 2.5        # Camera power consumption
    motor_idle: 1.0          # Motor idle power
    motor_active: 15.0       # Motor active power
    communication: 1.5       # WiFi/MQTT communication
    display: 0.3            # Small OLED display
  
  # Mode-specific multipliers
  mode_multipliers:
    high_performance: 1.0
    eco_mode: 0.6
    charging_mode: 0.4
    emergency_mode: 0.2

# Sunny Spot Management
sunny_spots:
  # Learning parameters
  learning:
    enabled: true
    min_power_threshold: 10.0    # W - Minimum power to record spot
    radius_meters: 5.0           # Merge spots within this radius
    learning_rate: 0.1           # Exponential moving average rate
    
  # Data management
  data_management:
    max_spots: 50               # Maximum number of spots to remember
    retention_days: 30          # Days to keep spot data
    cleanup_interval: 3600      # Seconds between cleanup runs
  
  # Navigation
  navigation:
    enable_auto_navigation: true
    min_efficiency_threshold: 0.5  # Only navigate to spots with >50% efficiency
    time_of_day_preference: true   # Prefer spots optimal for current time
    seasonal_adjustment: true      # Apply seasonal efficiency adjustments

# Charging Strategy
charging:
  # Charging modes
  modes:
    auto:
      description: "Automatic optimization based on conditions"
      solar_priority: true
      weather_aware: true
      schedule_aware: true
    
    manual:
      description: "Manual control of charging behavior"
      solar_priority: false
      weather_aware: false
      schedule_aware: false
    
    eco:
      description: "Maximum efficiency, minimal power consumption"
      solar_priority: true
      weather_aware: true
      schedule_aware: true
      power_saving_always: true
  
  # LiFePO4 specific charging parameters
  lifepo4:
    bulk_charge_voltage: 14.4     # V
    absorption_voltage: 14.6      # V
    float_voltage: 13.6           # V
    temperature_compensation: -0.003  # V/°C/cell
    max_charge_current: 10.0      # A

# Safety Configuration
safety:
  # Emergency thresholds
  emergency:
    critical_voltage: 10.0        # V - Immediate shutdown
    critical_temperature: 70.0    # °C - Emergency cooling needed
    max_discharge_current: 25.0   # A - Circuit protection
  
  # Monitoring intervals
  monitoring:
    safety_check_interval: 1.0    # Seconds between safety checks
    temperature_check_interval: 10.0  # Seconds between temperature checks
    voltage_trend_window: 60.0    # Seconds for voltage trend analysis
  
  # Actions
  actions:
    emergency_shutdown: true      # Enable emergency shutdown
    navigate_to_safety: true      # Navigate to safe location on emergency
    alert_notifications: true     # Send safety alerts via MQTT

# Integration Settings
integration:
  # MQTT Topics
  mqtt:
    battery_topic: "power/battery"
    solar_topic: "power/solar"
    consumption_topic: "power/consumption"
    mode_change_topic: "power/mode_change"
    sunny_spots_topic: "power/sunny_spots"
    alerts_topic: "power/alerts"
    commands_topic: "commands/power"
  
  # Cache settings
  cache:
    battery_ttl: 60              # Seconds to cache battery data
    solar_ttl: 60                # Seconds to cache solar data
    sunny_spots_ttl: 300         # Seconds to cache sunny spots
  
  # External services
  services:
    weather_service: true        # Use weather service for solar prediction
    navigation_service: true     # Integration with navigation for sunny spots
    safety_service: true         # Report to safety monitoring system

# Logging Configuration
logging:
  level: "INFO"
  modules:
    power_manager: "INFO"
    power_service: "INFO"
    sunny_spot_learning: "DEBUG"
    battery_monitoring: "INFO"
    solar_monitoring: "INFO"
  
  # Log rotation
  rotation:
    max_size_mb: 10
    backup_count: 5
    
# Development and Testing
development:
  # Simulation mode for testing without hardware
  simulation:
    enabled: false
    battery_discharge_rate: 0.01   # Per hour
    solar_generation_curve: true   # Simulate daily solar curve
    temperature_simulation: true   # Simulate temperature effects
  
  # Debug features
  debug:
    log_all_sensor_data: false
    save_power_history: true
    enable_test_commands: false
