# Computer Vision System Configuration

# Detection Settings
detection:
  confidence_threshold: 0.6        # Minimum confidence for object detection
  nms_threshold: 0.4              # Non-maximum suppression threshold
  max_detections: 50              # Maximum objects to detect per frame
  
# Performance Settings
performance:
  max_processing_time_ms: 100.0   # Maximum allowed processing time per frame
  target_fps: 30                  # Target frames per second
  enable_tpu: true                # Enable Coral TPU acceleration
  fallback_to_cpu: true           # Fall back to CPU if TPU unavailable
  
# Safety Settings
safety:
  person_detection_distance: 3.0  # Safety distance for people (meters)
  pet_detection_distance: 1.5     # Safety distance for pets (meters)
  emergency_response_time_ms: 100.0  # Maximum emergency response time
  
# Model Settings
models:
  primary_model_path: "models/custom/advanced_obstacles_v2.tflite"
  backup_model_path: "models/custom/lawn_obstacles_v1.tflite"
  fallback_model_path: "models/efficientdet_d0.tflite"
  model_update_check_interval: 3600  # Check for model updates every hour
  custom_models_path: "models/custom"
  enable_model_auto_update: true
  
  # Advanced specialized models
  specialized_models:
    grass_health: "models/custom/grass_health_analyzer_v2.tflite"
    weather_conditions: "models/custom/weather_condition_expert_v2.tflite"
    terrain_analysis: "models/custom/terrain_surface_analyzer_v2.tflite"
  
  # Model switching settings
  enable_dynamic_model_switching: true
  model_switching_confidence_threshold: 0.7
  
# Training Settings
training:
  enable_continuous_learning: true
  training_data_retention_days: 30
  min_training_samples: 100
  auto_retrain_threshold: 500     # Retrain after collecting this many samples
  
# Resource Limits
resources:
  max_memory_usage_mb: 512
  max_cpu_usage_percent: 80.0
  max_storage_usage_gb: 5.0
  
# Image Processing
image_processing:
  enable_noise_reduction: true
  enable_color_correction: true
  enable_image_stabilization: true
  enable_lighting_adjustment: true
  
# Data Storage
storage:
  training_images_path: "vision_data/training_images"
  models_path: "vision_data/models"
  logs_path: "vision_data/logs"
  
# MQTT Topics
mqtt:
  detection_topic: "vision/detections"
  frame_analysis_topic: "vision/frame_analysis"
  safety_alert_topic: "safety/vision_alert"
  command_topic: "commands/vision"
  response_topic: "responses/vision"
  
# Logging
logging:
  level: "INFO"
  enable_performance_logging: true
  enable_detection_logging: true
  log_rotation_size_mb: 50
  max_log_files: 10
  
# Object Detection Classes
object_classes:
  # Safety-critical objects (immediate stop)
  critical:
    - person
    - pet
    - hole
    - hose
    - cable
    
  # High priority objects (stop and assess)
  high_priority:
    - toy
    - furniture
    - tree
    - slope
    
  # Medium priority objects (slow down and monitor)
  medium_priority:
    - stone
    - wet_area
    
  # Low priority objects (log and continue)
  low_priority:
    - boundary
    
# Lighting Conditions
lighting:
  min_brightness: 50              # Minimum brightness for operation
  max_brightness: 200             # Maximum brightness for operation
  auto_adjust_exposure: true      # Automatically adjust camera exposure
  
# Weather Detection
weather:
  enable_rain_detection: true
  enable_fog_detection: true
  rain_texture_threshold: 15.0    # Texture measure threshold for rain
  fog_contrast_threshold: 20.0    # Contrast threshold for fog detection
  
# Debugging and Development
debug:
  enable_debug_mode: false
  save_debug_images: false
  debug_image_interval: 100       # Save every Nth frame when debugging
  enable_visualization: false     # Draw bounding boxes on images
  
# Integration Settings
integration:
  enable_sensor_fusion: true      # Integrate with ToF sensors for distance validation
  enable_navigation_feedback: true # Send obstacle data to navigation system
  enable_safety_integration: true # Integrate with safety monitoring system
