openapi: 3.1.0
info:
  title: LawnBerry WebUI REST API
  version: 0.1.0
  description: >-
    REST surfaces powering the seven LawnBerry WebUI pages. All endpoints
    require the shared operator credential unless otherwise noted.
servers:
  - url: https://mower.local
    description: On-device API gateway
security:
  - basicOperatorAuth: []
paths:
  /api/dashboard/state:
    get:
      summary: Retrieve live mower dashboard snapshot
      operationId: getDashboardState
      responses:
        '200':
          description: Dashboard telemetry snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardTelemetry'
      tags: [Dashboard]
  /api/dashboard/alerts:
    get:
      summary: List active safety and health alerts
      operationId: getDashboardAlerts
      responses:
        '200':
          description: Active alerts ordered by severity
          content:
            application/json:
              schema:
                type: object
                properties:
                  alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Alert'
      tags: [Dashboard]
  /api/map/zones:
    get:
      summary: Fetch current mowing zones and exclusion areas
      operationId: getMapZones
      responses:
        '200':
          description: Current map configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MapZoneCollection'
      tags: [Map Setup]
    put:
      summary: Replace mowing zones and exclusion areas
      operationId: updateMapZones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MapZoneUpdateRequest'
      responses:
        '200':
          description: Zones updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MapZoneCollection'
      tags: [Map Setup]
  /api/manual/command:
    post:
      summary: Issue a direct drive or blade command
      operationId: postManualCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualCommandRequest'
      responses:
        '202':
          description: Command accepted for execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManualCommandResponse'
      tags: [Manual Control]
  /api/mow/jobs:
    get:
      summary: List scheduled and running mow jobs
      operationId: listMowJobs
      responses:
        '200':
          description: Current job queue ordered by priority
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobs:
                    type: array
                    items:
                      $ref: '#/components/schemas/MowJob'
      tags: [Mow Planning]
    post:
      summary: Schedule a new mow job
      operationId: createMowJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MowJobCreateRequest'
      responses:
        '201':
          description: Job created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MowJob'
      tags: [Mow Planning]
  /api/mow/jobs/{jobId}:
    parameters:
      - $ref: '#/components/parameters/JobId'
    get:
      summary: Retrieve job details
      operationId: getMowJob
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MowJob'
      tags: [Mow Planning]
    delete:
      summary: Cancel a pending job
      operationId: deleteMowJob
      responses:
        '204':
          description: Job cancelled
      tags: [Mow Planning]
  /api/ai/datasets:
    get:
      summary: List captured datasets awaiting labeling/export
      operationId: listDatasets
      responses:
        '200':
          description: Dataset catalog
          content:
            application/json:
              schema:
                type: object
                properties:
                  datasets:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dataset'
      tags: [AI Training]
  /api/ai/datasets/export:
    post:
      summary: Request dataset export in COCO JSON and/or YOLO TXT formats
      operationId: requestDatasetExport
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetExportRequest'
      responses:
        '202':
          description: Export job accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetExportJob'
      tags: [AI Training]
  /api/settings/profile:
    get:
      summary: Retrieve mower configuration profile
      operationId: getSettingsProfile
      responses:
        '200':
          description: Current settings profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsProfile'
      tags: [Settings]
    put:
      summary: Update mower configuration profile
      operationId: updateSettingsProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsProfileUpdateRequest'
      responses:
        '200':
          description: Updated settings profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettingsProfile'
      tags: [Settings]
  /api/docs/index:
    get:
      summary: Retrieve Docs Hub manifest
      operationId: getDocsIndex
      security: []
      responses:
        '200':
          description: Documentation manifest
          content:
            application/json:
              schema:
                type: object
                properties:
                  entries:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocsEntry'
      tags: [Docs Hub]
components:
  securitySchemes:
    basicOperatorAuth:
      type: http
      scheme: basic
      description: >-
        Shared operator credential enforced for all control and data endpoints.
  parameters:
    JobId:
      name: jobId
      in: path
      required: true
      schema:
        type: string
        pattern: '^[0-9a-fA-F-]{36}$'
  schemas:
    DashboardTelemetry:
      type: object
      required: [mowerState, safety, metrics, lastUpdate]
      properties:
        mowerState:
          type: string
          enum: [idle, mowing, docking, charging, error]
        safety:
          type: object
          required: [emergencyStop, tilt, bladeActive]
          properties:
            emergencyStop:
              type: boolean
            tilt:
              type: boolean
            bladeActive:
              type: boolean
        metrics:
          $ref: '#/components/schemas/TelemetryMetrics'
        lastUpdate:
          type: string
          format: date-time
        cadenceHz:
          type: number
          minimum: 0.2
          maximum: 5
          default: 1
    TelemetryMetrics:
      type: object
      required: [batteryVoltage, batteryPercent, solarInputWatts]
      properties:
        batteryVoltage:
          type: number
        batteryPercent:
          type: number
          minimum: 0
          maximum: 100
        solarInputWatts:
          type: number
        gpsFixQuality:
          type: string
          enum: [none, float, fixed]
        localizationState:
          type: string
    Alert:
      type: object
      required: [id, severity, message, createdAt]
      properties:
        id:
          type: string
        severity:
          type: string
          enum: [info, warn, critical]
        message:
          type: string
        createdAt:
          type: string
          format: date-time
    MapZoneCollection:
      type: object
      required: [zones, exclusions, version]
      properties:
        version:
          type: string
        zones:
          type: array
          items:
            $ref: '#/components/schemas/MapZone'
        exclusions:
          type: array
          items:
            $ref: '#/components/schemas/MapZone'
    MapZone:
      type: object
      required: [id, name, polygon]
      properties:
        id:
          type: string
        name:
          type: string
        polygon:
          type: array
          minItems: 3
          items:
            type: array
            minItems: 2
            maxItems: 2
            items:
              type: number
    MapZoneUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/MapZoneCollection'
        - type: object
          required: [version]
          properties:
            version:
              type: string
              description: Optimistic concurrency token
    ManualCommandRequest:
      type: object
      required: [command, issuedAt]
      properties:
        command:
          type: string
          enum: [drive-forward, drive-reverse, turn-left, turn-right, blade-on, blade-off, stop]
        magnitude:
          type: number
          minimum: 0
          maximum: 1
        issuedAt:
          type: string
          format: date-time
    ManualCommandResponse:
      type: object
      required: [commandId, acceptedAt]
      properties:
        commandId:
          type: string
        acceptedAt:
          type: string
          format: date-time
    MowJob:
      type: object
      required: [jobId, status, windowStart, windowEnd, zoneId, createdAt]
      properties:
        jobId:
          type: string
        status:
          type: string
          enum: [queued, running, paused, complete, failed]
        windowStart:
          type: string
          format: date-time
        windowEnd:
          type: string
          format: date-time
        zoneId:
          type: string
        createdAt:
          type: string
          format: date-time
        progressPercent:
          type: number
          minimum: 0
          maximum: 100
    MowJobCreateRequest:
      type: object
      required: [zoneId, windowStart, windowEnd]
      properties:
        zoneId:
          type: string
        windowStart:
          type: string
          format: date-time
        windowEnd:
          type: string
          format: date-time
        bladeHeightMm:
          type: number
          minimum: 10
          maximum: 60
    Dataset:
      type: object
      required: [datasetId, imageCount, labeledCount, createdAt]
      properties:
        datasetId:
          type: string
        imageCount:
          type: integer
        labeledCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        lastReviewedAt:
          type: string
          format: date-time
          nullable: true
    DatasetExportRequest:
      type: object
      required: [datasetId, formats]
      properties:
        datasetId:
          type: string
        formats:
          type: array
          minItems: 1
          items:
            type: string
            enum: [coco-json, yolo-txt]
    DatasetExportJob:
      type: object
      required: [jobId, datasetId, status, requestedFormats, submittedAt]
      properties:
        jobId:
          type: string
        datasetId:
          type: string
        status:
          type: string
          enum: [queued, running, complete, failed]
        requestedFormats:
          type: array
          items:
            type: string
            enum: [coco-json, yolo-txt]
        submittedAt:
          type: string
          format: date-time
        completedAt:
          type: string
          format: date-time
          nullable: true
        artifactUrls:
          type: object
          additionalProperties:
            type: string
            format: uri
    SettingsProfile:
      type: object
      required: [hardware, network, simulation]
      properties:
        hardware:
          type: object
          properties:
            aiAcceleration:
              type: string
              enum: [coral-usb, hailo-hat, cpu]
            gpsMode:
              type: string
              enum: [rtk, fallback]
            sensorsValidated:
              type: boolean
        network:
          type: object
          properties:
            wifiSsid:
              type: string
            wifiSignalDbm:
              type: number
            ntripEndpoint:
              type: string
              format: uri
              nullable: true
        simulation:
          type: object
          properties:
            enabled:
              type: boolean
            reason:
              type: string
    SettingsProfileUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/SettingsProfile'
        - type: object
          required: [hardware]
    DocsEntry:
      type: object
      required: [id, title, category, url]
      properties:
        id:
          type: string
        title:
          type: string
        category:
          type: string
          enum: [setup, troubleshooting, compliance]
        url:
          type: string
          format: uri
