name: CI
on: [push, pull_request]

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install project dependencies (locked)
        run: uv sync --frozen

      - name: Install dev tools
        run: pip install ruff

      - name: Lint (ruff)
        run: ruff check .

      - name: Run pytest (SIM_MODE=1)
        env:
          SIM_MODE: '1'
        run: uv run pytest -q
