name: ci
on: [push, pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --all-extras --dev
      - run: ruff check .
      - run: ruff format --check .
      - run: black --check .
      - run: mypy --strict src || true
      - run: SIM_MODE=1 LBY_ACCEL=cpu uv run pytest -q || true
      - name: Fail on TODOs
        run: "! git grep -nE 'TODO(?!\\(v3\\))' -- ':!docs' || (echo 'Unapproved TODOs found' && exit 1)"
